services:
  app:
    build: .
    container_name: teste_pratico_app
    volumes:
      - .:/var/www/html
    environment:
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - MYSQL_HOST=${MYSQL_HOST}
    networks:
      - teste_pratico_net

  nginx:
    image: nginx:alpine
    container_name: teste_pratico_nginx
    ports:
      - "8080:80"
    volumes:
      - .:/var/www/html
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app
    networks:
      - teste_pratico_net

  db:
    image: mysql:8.0
    container_name: teste_pratico_db
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    ports:
      - "3307:3306"
    networks:
      - teste_pratico_net

  frontend:
    image: node:20-alpine
    container_name: teste_pratico_frontend
    working_dir: /app
    volumes:
      - ./frontend:/app
    ports:
      - "5173:5173" 
    command: npm run dev -- --host 
    networks:
      - teste_pratico_net

networks:
  teste_pratico_net:
    driver: bridge